# Generated by Django 4.2.5 on 2023-09-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_question_choice_text_remove_question_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
